[BSE-4389] Add Bodo Platform SDK Guide in the quick start.
bodo-ai/Bodo pull request #84
Opened 2024-12-20 13:19 UTC by mbojanowski

## Changes included in this PR
Add Bodo Platform SDK Guide in the quick start.  I reused existing guide.

## Testing strategy

## User facing changes

## Checklist
- [ ] Pipelines passed before requesting review. To run CI you must include `[run CI]` in your commit message.
- [ ] I am familiar with the [Contributing Guide](https://github.com/bodo-ai/Bodo/blob/main/CONTRIBUTING.md) 
- [ ] I have installed + ran pre-commit hooks.

2024-12-20 13:21 UTC, mbojanowski commented
We can create additional guide which is a little more simple but, then we will need to maintain two guides, which is not ideal.

2024-12-20 13:28 UTC, ehsantn requested changes
The intention of the issue wasn't moving the guide. The intention is adding a very simple SDK example to the cloud quick start.

2024-12-20 16:15 UTC, ehsantn commented on docs/mkdocs.yml
> -          - Bodo Platform SDK guide : guides/using_bodo_platform/bodo_platform_sdk_guide.md
Let's undo this change.

2024-12-20 17:15 UTC, mbojanowski commented on docs/mkdocs.yml
> -          - Bodo Platform SDK guide : guides/using_bodo_platform/bodo_platform_sdk_guide.md
Done

2024-12-23 14:45 UTC, mbojanowski commented
I got few improvements from @marquisdepolis:

* Rename similar sounding Bodo Platform SDK pages to explain what they are!
  * now we have `Platform SDK Quick Start` and `Platform SDK Guide`
  * we also agreed on removing `docs/docs/installation_and_setup/platform_sdk.md` as this is already in both `Platform SDK Quick Start` and `Platform SDK Guide`

* Put bodo platform sdk left hand side as second suggestion"

![image](https://github.com/user-attachments/assets/5046401b-a0b2-44a7-b980-5fad3e3cba7f)
not sure about that as first I think user should also understood Bodo Platform in general.

* How to run a piece of code on a piece of data on one's laptop
   * this will require feature in Bodo Platform, right now not supported

* We should support reading in files from local environment
   * this also will require feature in Bodo Platform, right now not supported

* Add reference on source to be github, s3, workspace etc -- show how. Change code to read from a public s3 bucket and does some work on it - in the example
   * looks like we don't have public S3/Github with examples right now, 

* Change the search too to hide older pages:
  * search is not showing older pages, when you type `Bodo SDK` it will first show all pages that have `Bodo` and `SDK` but also it will show all pages with only Bodo or SDK thats why we got so many results

2024-12-23 15:30 UTC, mbojanowski commented
I also changed some left menu list:

from:
![image](https://github.com/user-attachments/assets/225dd682-0b3f-42cc-976c-7f5edc27ec55)

to:
![image](https://github.com/user-attachments/assets/b2e75456-a56f-45df-a587-321f80d291ae)


from:
![image](https://github.com/user-attachments/assets/dc5efc2a-52fe-4fcb-bcad-8a2489558897)

to:
![image](https://github.com/user-attachments/assets/163069b4-2070-4fe4-b7bb-69be99e85e93)

2024-12-23 15:44 UTC, mbojanowski commented
Form this:
![image](https://github.com/user-attachments/assets/088ac07e-0b40-44c5-921f-c188eb4f0fe8)

to:

![image](https://github.com/user-attachments/assets/b2c3d3db-e3db-4c1d-bd49-2b32cfc1b2d0)

2024-12-23 15:47 UTC, mbojanowski commented
Form this:
![image](https://github.com/user-attachments/assets/26137381-0387-42b3-b031-64aa1824b055)

to this:
![image](https://github.com/user-attachments/assets/cddf1a0a-1627-451f-948f-261e708d4f3d)

2024-12-24 05:08 UTC, marquisdepolis approved these changes

2024-12-24 14:55 UTC, ehsantn approved these changes
Thanks @mbojanowski !

2024-12-30 11:19 UTC, merged